sudo: required
dist: trusty
language: cpp
cache: apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt5-qmake qt5-default qtbase5-dev libbotan1.10-dev gcc-4.8

script:
  - qmake
  - make
