sudo: required
dist: trusty
language: cpp
cache: apt
env: COMPILER=g++-5

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools gcc-5 g++-5 libboost-all-dev

script:
    - qmake
    - make
    - ./test/P2S_App_Test/tst_p2s_testtest #run App test
