sudo: required
dist: trusty
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - qt5-qmake
            - qt5-default
            - qtbase5-dev
            - qttools5-dev-tools
            - libboost-all-dev
            - gcc-5
            - g++-5

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

script:
    - $CXX --version
    - qmake
    - make
    - ./test/P2S_App_Test/tst_p2s_testtest #run App test
