sudo: required
dist: trusty
language: cpp
cache: apt

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qt5-qmake
            - qt5-default
            - qtbase5-dev
            - qttools5-dev-tools
            - gcc-5 g++-5
            - libboost-all-dev
            - g++-5

before_install:
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
    - qmake
    - make
    - ./test/P2S_App_Test/tst_p2s_testtest #run App test
